# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_schema.ipynb.

# %% auto 0
__all__ = ['StrictBaseModel', 'LaxBaseModel']

# %% ../nbs/00_schema.ipynb 3
import pydantic
from pydantic import BaseModel, Field
from openai import ChatCompletion

# %% ../nbs/00_schema.ipynb 4
class StrictBaseModel(BaseModel):
    class Config:
        strict = True
        extra = "forbid"

class LaxBaseModel(BaseModel):
    class Config:
        extra = "allow"
